export type TextVariant =
  | 'primary'
  | 'accent'
  | 'error'
  | 'warning'
  | 'secondary'
  | 'secondary-muted'
  | 'underlined'
export type TextSize = 's' | 'm' | 'l' | 'xl' | 'xxl'
export type TextAlign = 'right' | 'left' | 'center'
export type TextWeight = '400' | '500' | '600' | '700'
